export const PROPERTY_ADD_REQUEST = "PROPERTY_ADD_REQUEST";
export const PROPERTY_ADD_SUCCESS = "PROPERTY_ADD_SUCCESS";
export const PROPERTY_ADD_FAIL = "PROPERTY_ADD_FAIL";

export const FACILITY_ADD_REQUEST = "FACILITYTY_ADD_REQUEST";
export const FACILITY_ADD_SUCCESS = "FACILITY_ADD_SUCCESS";
export const FACILITY_ADD_FAIL = "FACILITY_ADD_FAIL";
