export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_FETCH_RESET = "USER_FETCH_RESET";
export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";

export const PROPERTY_FETCH_RESET = "PROPERTY_FETCH_RESET";
export const PROPERTY_FETCH_REQUEST = "PROPERTY_FETCH_REQUEST";
export const PROPERTY_FETCH_SUCCESS = "PROPERTY_FETCH_SUCCESS";
export const PROPERTY_FETCH_FAIL = "PROPERTY_FETCH_FAIL";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";

export const OWNER_FETCH_RESET = "OWNER_FETCH_RESET";
export const OWNER_FETCH_REQUEST = "OWNER_FETCH_REQUEST";
export const OWNER_FETCH_SUCCESS = "OWNER_FETCH_SUCCESS";
export const OWNER_FETCH_FAIL = "OWNER_FETCH_FAIL";
